### PR TITLE
Add kafka logger

### PR DESCRIPTION
**Pull request by 9il**
- [x] expose producer configs such as compression, retries, retry delay, batching (already done in init commit)
- [x] possibility to set the value by a format string (already done in init commit)
- [x] multiple topics per single kafka-log
- [x] possibility to set the key by a format string
- [x] use `producev` and add timestamp
- [ ] add kafka-readme
- [ ] implement missing partition_hash etc

### CODE REVIEW

**Comment by yannick** [comment]
recap from our discussion

**Comment by yannick** [comment]
<>

**Comment by 9il** [comment]
> expose producer configs such as compression, retries, retry delay, batching

This already should works

**Comment by 9il** [comment]
And topics configs too

**Review by yannick — COMMENTED** [review]
the info in the readme.md this should be moved to a special file, otherwise we can't get it upstream

**Comment by 9il** [comment]
ok

**Comment by 9il** [comment]
filled https://github.com/edenhill/librdkafka/issues/934

**Pull request closed without merging**
